version: "3"

services:
    terminal-frontend:
        build: ./terminal-frontend
        volumes:
            - "./terminal-frontend/.nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        ports:
            - "80:80"
        depends_on: 
            - terminal-backend
        
    terminal-backend:
        build: .
